accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'accounts'

urlpatterns = [
  path('signup/', views.signup, name='signup'),
  path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
  path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
    path('accounts/', include('accounts.urls')),
]

photo/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings
app_name = 'photo'

urlpatterns = [
    path('like<int:photo_id>/', PhotoLike.as_view(), name='like'),
    path('favorite<int:photo_id>/', PhotoFavorite.as_view(), name='favorite'),
    
    path('create/', PhotoCreate.as_view(), name='create'),
    path('delete/<int:pk>/', PhotoDelete.as_view(), name='delete'),
    path('update/<int:pk>/', PhotoUpdate.as_view(), name='update'),
    path('detail/<int:pk>/', PhotoDetail.as_view(), name='detail'),

    path('like/', PhotoLikeList.as_view(), name='like_list'),
    path('favorite/', PhotoFavoriteList.as_view(), name='favorite_list'),
    path('mylist/', PhotoMyList.as_view(), name='mylist'),

    path('', PhotoList.as_view(), name='index'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

photo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Photo(models.Model):
  author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
  text = models.TextField(blank=True)
  image = models.ImageField(upload_to='timeline_photo/%Y/%m/%d')
  created = models.DateTimeField(auto_now_add=True)
  update = models.DateTimeField(auto_now=True)

  like = models.ManyToManyField(User, related_name='like_post', blank=True)
  favorite = models.ManyToManyField(User, related_name='favorite_post', blank=True)

  def __str__(self):
    return 'text : '+self.text

  class Meta:
    ordering = ['-created']
    
  def get_absolute_url(self):
    return reverse('photo:detail', args=[self.id])

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User

def signup(request):
  if request.method == 'POST':
    # 입력 받은 내용을 이용 회원 객체 생성
    username = request.POST.get('username')
    password = request.POST.get('password')
    password2 = request.POST.get('password2')
    print(username, password, password2)

    user = User()
    user.username = username
    user.password = password
    user.set_password(password)
    user.save()
    return render(request, 'accounts/signup_complete.html')
  else:
    context_values = {'form':'this is form'}
    return render(request, 'accounts/signup.html', context_values)

photo/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.contrib import messages

from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.base import View
from .models import Photo
from urllib.parse import urlparse

class PhotoList(ListView):
  model = Photo
  template_name_suffix = '_list' # template_name vs template_name_suffix와 차이가 존재함


class PhotoCreate(CreateView):
  model = Photo
  fields = ['text','image']
  template_name_suffix = '_create'
  success_url = '/'

  def form_valid(self, form):
    form.instance.author_id = self.request.user.id # ???
    if form.is_valid():
      form.instance.save()
      return redirect('/')
    else:
      return self.render_to_response({'form':form})


class PhotoUpdate(UpdateView):
  model = Photo
  fields = ['text', 'image']
  template_name_suffix = '_update'
  success_url = '/'

  def dispatch(self, request, *args, **kwargs):
    object = self.get_object()
    if object.author != request.user:
      messages.warning(request, '수정할 권한이 없어요.')
      return HttpResponseRedirect('/')
    else:
      return super(PhotoUpdate, self).dispatch(request, *args, **kwargs)

class PhotoDelete(DeleteView):
  model = Photo
  template_name_suffix = '_delete'
  success_url = '/'

  def dispatch(self, request, *args, **kwargs):
    object = self.get_object()
    if object.author != request.user:
      messages.warning(request, '삭제할 권한이 없어요.')
      return HttpResponseRedirect('/')
    else:
      return super(PhotoDelete, self).dispatch(request, *args, **kwargs)

class PhotoDetail(DetailView):
  model = Photo
  template_name_suffix = '_detail'
  success_url = '/'


class PhotoLike(View):
  def get(self, request, *args, **kwargs):
    if not request.user.is_authenticated:
      return HttpResponseForbidden()
    else:
      if 'photo_id' in kwargs:
        photo_id = kwargs['photo_id']
        photo = Photo.objects.get(pk=photo_id)
        user = request.user
        if user in photo.like.all():
          photo.like.remove(user)
        else:
          photo.like.add(user)

      referer_url = request.META.get('HTTP_REFERER')
      path = urlparse(referer_url).path
      return HttpResponseRedirect(path)


class PhotoFavorite(View):
  def get(self, request, *args, **kwargs):
    if not request.user.is_authenticated:
      return HttpResponseForbidden()
    else:
      if 'photo_id' in kwargs:
        photo_id = kwargs['photo_id']
        photo = Photo.objects.get(pk=photo_id)
        user = request.user
        if user in photo.like.all():
          photo.favorite.remove(user)
        else:
          photo.favorite.add(user)

      referer_url = request.META.get('HTTP_REFERER')
      path = urlparse(referer_url).path
      return HttpResponseRedirect(path)


class PhotoLikeList(ListView):
  model = Photo
  template_name = 'photo/photo_list.html'

  def dispatch(self, request, *args, **kwargs):
    if not request.user.is_authenticated:
      messages.warning(request, '로그인후 가능해요')
      return HttpResponseRedirect('/')
    return super(PhotoLikeList, self).dispatch(request, *args, **kwargs)

  def get_queryset(self):
    user = self.request.user
    queryset = user.like_post.all()
    return queryset


class PhotoFavoriteList(ListView):
  model = Photo
  template_name = 'photo/photo_list.html'

  def dispatch(self, request, *args, **kwargs):
    if not request.user.is_authenticated:
      messages.warning(request, '로그인후 이용 가능해요')
      return HttpResponseRedirect('/')
    return super(PhotoFavoriteList, self).dispatch(request, *args, **kwargs)

  def get_queryset(self):
    user = self.request.user
    queryset = user.favorite_post.all()
    return queryset


class PhotoMyList(ListView):
  model = Photo
  template_name = 'photo/photo_mylist.html'

  def dispatch(self, request, *args, **kwargs):
    if not request.user.is_authenticated:
      messages.warning(request, '로그인후 이용 가능해요')
      return HttpResponseRedirect('/')
    return super(PhotoMyList, self).dispatch(request, *args, **kwargs)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col"></div>
  <div class="col-6">
    <div class="alert alert-primary" role="alert">
      로그인 정보를 입력해주세요.</div>
      <form action='' method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="login" class="btn btn-outline-primary">
      </form>
    </div>
    <div class="col"></div>
  </div>


{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block title %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col"></div>
  <div class="col-6">
    <div class="alert alert-primary" role="alert">
      로그아웃 되었어요.</div>
    <a href="{% url 'accounts:login' %}" class="btn btn-outline-success">Login Again</a>
    </div>
    <div class="col"></div>
  </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
  <div class="col"></div>
  <div class="col-6">
    <form action="" method="post">
      <div class="alert alert-info">계정 정보를 입력해주세요</div>
        {% csrf_token %}
        <label>Username : <input type="text" name="username"></label>
        <label>Password : <input type="password" name="password"></label>
        <label>Repeat Password : <input type="password" name="password2"></label>
      <input type="submit" value="Sign up" class="btn btn-outline-info">
      </form>
  </div>
  <div class="col"></div>

</div>
{% endblock %}

accounts/templates/accounts/signup_complete.html
{% extends 'base.html' %}

{% block title %}{% endblock %}
{% block content %}

<div class="row">
  <div class="col"></div>
  <div class="col-6">
    <div class="alert alert-primary" role="alert">
      축하합니다.<br>
      회원 가입이 성공적으로 이루어졌습니다.
    </div>
    <a href="{% url 'accounts:login' %}">로그인 페이지로 이동</a>
  </div>
  <div class="col"></div>

</div>
{% endblock %}

photo/templates/photo/photo_create.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col"></div>
  <div class="col-12 col-xl-8 col-md-8">
    <div class="alert alert-primary" role="alert">
      모든 부분을 다 채워넣어주세요!!!
    </div>
    <form action="" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      
      {{form.as_p}}
      <input type="submit" value="Upload" class="btn btn-primary">
    </form>
  </div>
  <div class="col"></div>
</div>

{% endblock %}

photo/templates/photo/photo_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="alert alert-primary" role="alert">
  정말로 {{object}}를 삭제 하시겠어요?
</div>
<form action="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="Delete OK">
</form>
{% endblock %}

photo/templates/photo/photo_detail.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-4 col-md-4">
        <div class="card" style="">
            <img src=" {{ object.image.url }}" class="card-img-top" alt="...">
            <div class="card-body">

                <h5 class="card-title">{{ object.author }}</h5>
                <p class="card-text"> {{ object.text }} </p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                        <a href="{% url 'photo:like' object.id %}" class="float-left btn-like {%if user in object.like.all %} active {%endif%}">좋아요!</a>
                        {% if object.like.all.count %}
                        <span class = "float-left">
                            {{object.like.all.count}}
                        </span>
                        {% endif %}
                        <a href="{% url 'photo:favorite' object.id %}" class="float-right btn-favorite {%if user in object.favorite.all %} active {%endif%}">저장하기!</a>
                    </li>
                <li class="list-group-item">생성일 : {{ object.created }}</li>
                <li class="list-group-item">

                    {% load disqus_tags %}
                    <div class="card-body">
                        {% disqus_show_comments %}
                    </div>
                </li>
            </ul>
            <div class="card-body">
                <a href="{% url 'photo:update' object.id %}" class="card-link">수정하기</a>
                <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제하기</a>
            </div>
        </div>
    </div>

    <div class="col"></div>
</div>
{% endblock %}

photo/templates/photo/photo_list.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}

<div class='container'>
    <div class="row">
        <div class="col"></div>
        <div class="col-5">
            {% for object in object_list %}

            <div class="card">
                <div class="card-header">
                    {{ object.author }}
                </div>
                <img src=" {{ object.image.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <p class="card-text"> {{ object.text }} </p>
                </div>
                <ul class="list-group list-group-flush">

                   <li class="list-group-item">
                        <a href="{% url 'photo:like' object.id %}" class="float-left btn-like {%if user in object.like.all %} active {%endif%}">좋아요!</a>
                        {% if object.like.all.count %}
                        <span class = "float-left">
                            {{object.like.all.count}}
                        </span>
                        {% endif %}
                        <a href="{% url 'photo:favorite' object.id %}" class="float-right btn-favorite {%if user in object.favorite.all %}active{%endif%}">저장하기!</a>
                    </li>
                    <li class="list-group-item">생성일 : {{ object.created }}</li>
                </ul>
                <div class="card-body">
                    <a href="{% url 'photo:detail' object.id %}" class="card-link">댓글달기</a>
                    <a href="{% url 'photo:update' object.id %}" class="card-link">수정하기</a>
                    <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제하기</a>

                </div>

            </div>
            {% endfor %}

        </div>
        <div class="col">
            {% load static %}
            <div class="card" style="">
              {% if user.is_authenticated %}
                <img src="{% static 'images/cheetha.jpg' %}" class="card-img-top">
              {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ user.username }}</h5>
                    <p class="card-text">MY STORY를 확인해보세요!</p>
                    <a href="{% url 'photo:mylist' %}" class="btn btn-primary">나의 STORY로 이동 </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

photo/templates/photo/photo_mylist.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<style>

</style>

<div class="row">
  <div class="col-md-12">
    <div id="mdb-lightbox-ui"></div>
    <div class="mdb-lightbox no-margin">
      <div class="row">
        {% for object in object_list %}
        {% if object.author == request.user %}
        <figure class="col-md-4">
          <div style="width: 18rem;">
            <img src="{{object.image.url}}" class="card-img-top" alt="...">
          </div>
        </figure>
        {% endif %}
        {% endfor %}
      </div>
    </div>
    <div class="col"></div>
  </div>
</div>

{% endblock %}

photo/templates/photo/photo_update.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
  <div class="col"></div>
  <div class="col-12 col-xl-8 col-md-8">
    <form action="" method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="Update">
    </form>
  </div>
  <div class="col"></div>
</div>
{% endblock %}